repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        exclude: ^(open_data_client/|app/alembic/|ui/app.py|.*__init__\.py$)
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: python
        types_or: [python, pyi]
        args: ["--fix", "--config", "pyproject.toml"]
        require_serial: true
        exclude: ^(open_data_client/|app/alembic/|ui/app.py|.*__init__\.py$)
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        types_or: [python, pyi]
        args: ["--config", "pyproject.toml"]
        require_serial: true
        exclude: ^(open_data_client/|app/alembic/|ui/app.py|.*__init__\.py$)
